// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error)
	GetScan(ctx context.Context, id uuid.UUID) (Scan, error)
	UpdateScanStatus(ctx context.Context, arg UpdateScanStatusParams) (Scan, error)
}

var _ Querier = (*Queries)(nil)
