// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createScan = `-- name: CreateScan :one
INSERT INTO scans (
    id,
    url
) VALUES (
    $1,
    $2
)
RETURNING
    id,
    url,
    status,
    error_message,
    created_at,
    updated_at
`

type CreateScanParams struct {
	ID  uuid.UUID `json:"id"`
	URL string    `json:"url"`
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, createScan, arg.ID, arg.URL)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.URL,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScan = `-- name: GetScan :one
SELECT
    id,
    url,
    status,
    error_message,
    created_at,
    updated_at
FROM scans
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetScan(ctx context.Context, id uuid.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, getScan, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.URL,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScanStatus = `-- name: UpdateScanStatus :one
UPDATE scans
SET
    status = $1,
    error_message = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING
    id,
    url,
    status,
    error_message,
    created_at,
    updated_at
`

type UpdateScanStatusParams struct {
	Status       ScanStatus `json:"status"`
	ErrorMessage string     `json:"error_message"`
	ID           uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateScanStatus(ctx context.Context, arg UpdateScanStatusParams) (Scan, error) {
	row := q.db.QueryRow(ctx, updateScanStatus, arg.Status, arg.ErrorMessage, arg.ID)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.URL,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
