/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ScanStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        Scan: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string;
            status: components["schemas"]["ScanStatus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
