// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ReportFormat string

const (
	ReportFormatJson ReportFormat = "json"
	ReportFormatPdf  ReportFormat = "pdf"
)

func (e *ReportFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportFormat(s)
	case string:
		*e = ReportFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportFormat: %T", src)
	}
	return nil
}

type NullReportFormat struct {
	ReportFormat ReportFormat `json:"report_format"`
	Valid        bool         `json:"valid"` // Valid is true if ReportFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportFormat) Scan(value interface{}) error {
	if value == nil {
		ns.ReportFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportFormat), nil
}

type ReviewStatus string

const (
	ReviewStatusPending       ReviewStatus = "pending"
	ReviewStatusPassed        ReviewStatus = "passed"
	ReviewStatusFailed        ReviewStatus = "failed"
	ReviewStatusNotApplicable ReviewStatus = "not_applicable"
)

func (e *ReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatus(s)
	case string:
		*e = ReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatus: %T", src)
	}
	return nil
}

type NullReviewStatus struct {
	ReviewStatus ReviewStatus `json:"review_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatus), nil
}

type ScanStatus string

const (
	ScanStatusQueued    ScanStatus = "queued"
	ScanStatusRunning   ScanStatus = "running"
	ScanStatusCompleted ScanStatus = "completed"
	ScanStatusFailed    ScanStatus = "failed"
	ScanStatusCancelled ScanStatus = "cancelled"
)

func (e *ScanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScanStatus(s)
	case string:
		*e = ScanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScanStatus: %T", src)
	}
	return nil
}

type NullScanStatus struct {
	ScanStatus ScanStatus `json:"scan_status"`
	Valid      bool       `json:"valid"` // Valid is true if ScanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScanStatus), nil
}

type ViolationImpact string

const (
	ViolationImpactCritical ViolationImpact = "critical"
	ViolationImpactSerious  ViolationImpact = "serious"
	ViolationImpactModerate ViolationImpact = "moderate"
	ViolationImpactMinor    ViolationImpact = "minor"
)

func (e *ViolationImpact) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ViolationImpact(s)
	case string:
		*e = ViolationImpact(s)
	default:
		return fmt.Errorf("unsupported scan type for ViolationImpact: %T", src)
	}
	return nil
}

type NullViolationImpact struct {
	ViolationImpact ViolationImpact `json:"violation_impact"`
	Valid           bool            `json:"valid"` // Valid is true if ViolationImpact is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullViolationImpact) Scan(value interface{}) error {
	if value == nil {
		ns.ViolationImpact, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ViolationImpact.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullViolationImpact) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ViolationImpact), nil
}

type ActivityLog struct {
	ID         uuid.UUID          `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ManualReview struct {
	ID        uuid.UUID          `json:"id"`
	ScanID    uuid.UUID          `json:"scan_id"`
	Status    ReviewStatus       `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ManualReviewItem struct {
	ID             uuid.UUID          `json:"id"`
	ManualReviewID uuid.UUID          `json:"manual_review_id"`
	Criterion      string             `json:"criterion"`
	Instruction    string             `json:"instruction"`
	Status         ReviewStatus       `json:"status"`
	Notes          string             `json:"notes"`
	Position       int32              `json:"position"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID          uuid.UUID          `json:"id"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectMember struct {
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Report struct {
	ID          uuid.UUID          `json:"id"`
	ScanID      uuid.UUID          `json:"scan_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	Format      ReportFormat       `json:"format"`
	Filename    string             `json:"filename"`
	ContentType string             `json:"content_type"`
	Content     []byte             `json:"content"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Scan struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	Url            string             `json:"url"`
	Status         ScanStatus         `json:"status"`
	PageTitle      string             `json:"page_title"`
	AutomatedScore int16              `json:"automated_score"`
	CriticalCount  int32              `json:"critical_count"`
	SeriousCount   int32              `json:"serious_count"`
	ModerateCount  int32              `json:"moderate_count"`
	MinorCount     int32              `json:"minor_count"`
	ErrorMessage   string             `json:"error_message"`
	DurationMs     int64              `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type ScannedPage struct {
	ID        uuid.UUID          `json:"id"`
	ScanID    uuid.UUID          `json:"scan_id"`
	Url       string             `json:"url"`
	Title     string             `json:"title"`
	Language  string             `json:"language"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	CsrfHash   string             `json:"csrf_hash"`
	UserAgent  string             `json:"user_agent"`
	IpAddress  string             `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Violation struct {
	ID            uuid.UUID          `json:"id"`
	ScannedPageID uuid.UUID          `json:"scanned_page_id"`
	RuleID        string             `json:"rule_id"`
	Impact        ViolationImpact    `json:"impact"`
	Description   string             `json:"description"`
	Help          string             `json:"help"`
	HelpUrl       string             `json:"help_url"`
	Tags          []string           `json:"tags"`
	ReviewStatus  ReviewStatus       `json:"review_status"`
	Notes         string             `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ViolationNode struct {
	ID             uuid.UUID          `json:"id"`
	ViolationID    uuid.UUID          `json:"violation_id"`
	Html           string             `json:"html"`
	Target         []string           `json:"target"`
	FailureSummary string             `json:"failure_summary"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
