// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (
    project_id,
    user_id,
    role
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (project_id, user_id)
DO UPDATE SET role = EXCLUDED.role
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const cancelScan = `-- name: CancelScan :one
UPDATE scans
SET
    status = 'cancelled',
    error_message = '',
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status IN ('queued', 'running')
  AND EXISTS (
      SELECT 1
      FROM project_members
      WHERE project_members.project_id = scans.project_id
        AND project_members.user_id = $2
  )
RETURNING
    id,
    project_id,
    created_by,
    url,
    status,
    page_title,
    automated_score,
    critical_count,
    serious_count,
    moderate_count,
    minor_count,
    error_message,
    duration_ms,
    created_at,
    updated_at
`

type CancelScanParams struct {
	ScanID uuid.UUID `json:"scan_id"`
	UserID uuid.UUID `json:"user_id"`
}

type CancelScanRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	Url            string             `json:"url"`
	Status         ScanStatus         `json:"status"`
	PageTitle      string             `json:"page_title"`
	AutomatedScore int16              `json:"automated_score"`
	CriticalCount  int32              `json:"critical_count"`
	SeriousCount   int32              `json:"serious_count"`
	ModerateCount  int32              `json:"moderate_count"`
	MinorCount     int32              `json:"minor_count"`
	ErrorMessage   string             `json:"error_message"`
	DurationMs     int64              `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CancelScan(ctx context.Context, arg CancelScanParams) (CancelScanRow, error) {
	row := q.db.QueryRow(ctx, cancelScan, arg.ScanID, arg.UserID)
	var i CancelScanRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Url,
		&i.Status,
		&i.PageTitle,
		&i.AutomatedScore,
		&i.CriticalCount,
		&i.SeriousCount,
		&i.ModerateCount,
		&i.MinorCount,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeScan = `-- name: CompleteScan :one
UPDATE scans
SET
    status = 'completed',
    page_title = $1,
    automated_score = $2,
    critical_count = $3,
    serious_count = $4,
    moderate_count = $5,
    minor_count = $6,
    duration_ms = $7,
    error_message = '',
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $8
  AND status = 'running'
RETURNING
    id,
    project_id,
    created_by,
    url,
    status,
    page_title,
    automated_score,
    critical_count,
    serious_count,
    moderate_count,
    minor_count,
    error_message,
    duration_ms,
    created_at,
    updated_at
`

type CompleteScanParams struct {
	PageTitle      string    `json:"page_title"`
	AutomatedScore int16     `json:"automated_score"`
	CriticalCount  int32     `json:"critical_count"`
	SeriousCount   int32     `json:"serious_count"`
	ModerateCount  int32     `json:"moderate_count"`
	MinorCount     int32     `json:"minor_count"`
	DurationMs     int64     `json:"duration_ms"`
	ID             uuid.UUID `json:"id"`
}

type CompleteScanRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	Url            string             `json:"url"`
	Status         ScanStatus         `json:"status"`
	PageTitle      string             `json:"page_title"`
	AutomatedScore int16              `json:"automated_score"`
	CriticalCount  int32              `json:"critical_count"`
	SeriousCount   int32              `json:"serious_count"`
	ModerateCount  int32              `json:"moderate_count"`
	MinorCount     int32              `json:"minor_count"`
	ErrorMessage   string             `json:"error_message"`
	DurationMs     int64              `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CompleteScan(ctx context.Context, arg CompleteScanParams) (CompleteScanRow, error) {
	row := q.db.QueryRow(ctx, completeScan,
		arg.PageTitle,
		arg.AutomatedScore,
		arg.CriticalCount,
		arg.SeriousCount,
		arg.ModerateCount,
		arg.MinorCount,
		arg.DurationMs,
		arg.ID,
	)
	var i CompleteScanRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Url,
		&i.Status,
		&i.PageTitle,
		&i.AutomatedScore,
		&i.CriticalCount,
		&i.SeriousCount,
		&i.ModerateCount,
		&i.MinorCount,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countRecentScansByUser = `-- name: CountRecentScansByUser :one
SELECT COUNT(*)
FROM scans
WHERE created_by = $1
  AND created_at >= $2
`

type CountRecentScansByUserParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	SinceTime pgtype.Timestamptz `json:"since_time"`
}

func (q *Queries) CountRecentScansByUser(ctx context.Context, arg CountRecentScansByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentScansByUser, arg.UserID, arg.SinceTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :exec
INSERT INTO activity_logs (
    id,
    user_id,
    project_id,
    action,
    entity_type,
    entity_id,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateActivityLogParams struct {
	ID         uuid.UUID   `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	ProjectID  pgtype.UUID `json:"project_id"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error {
	_, err := q.db.Exec(ctx, createActivityLog,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	return err
}

const createManualReview = `-- name: CreateManualReview :one
INSERT INTO manual_reviews (
    id,
    scan_id
) VALUES (
    $1,
    $2
)
RETURNING
    id,
    scan_id,
    status,
    created_at,
    updated_at
`

type CreateManualReviewParams struct {
	ID     uuid.UUID `json:"id"`
	ScanID uuid.UUID `json:"scan_id"`
}

func (q *Queries) CreateManualReview(ctx context.Context, arg CreateManualReviewParams) (ManualReview, error) {
	row := q.db.QueryRow(ctx, createManualReview, arg.ID, arg.ScanID)
	var i ManualReview
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManualReviewItem = `-- name: CreateManualReviewItem :one
INSERT INTO manual_review_items (
    id,
    manual_review_id,
    criterion,
    instruction,
    position
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    manual_review_id,
    criterion,
    instruction,
    status,
    notes,
    position,
    created_at,
    updated_at
`

type CreateManualReviewItemParams struct {
	ID             uuid.UUID `json:"id"`
	ManualReviewID uuid.UUID `json:"manual_review_id"`
	Criterion      string    `json:"criterion"`
	Instruction    string    `json:"instruction"`
	Position       int32     `json:"position"`
}

func (q *Queries) CreateManualReviewItem(ctx context.Context, arg CreateManualReviewItemParams) (ManualReviewItem, error) {
	row := q.db.QueryRow(ctx, createManualReviewItem,
		arg.ID,
		arg.ManualReviewID,
		arg.Criterion,
		arg.Instruction,
		arg.Position,
	)
	var i ManualReviewItem
	err := row.Scan(
		&i.ID,
		&i.ManualReviewID,
		&i.Criterion,
		&i.Instruction,
		&i.Status,
		&i.Notes,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id,
    owner_id,
    name,
    description
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    owner_id,
    name,
    description,
    created_at,
    updated_at
`

type CreateProjectParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerID     uuid.UUID `json:"owner_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    id,
    scan_id,
    created_by,
    format,
    filename,
    content_type,
    content
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id,
    scan_id,
    created_by,
    format,
    filename,
    content_type,
    content,
    created_at
`

type CreateReportParams struct {
	ID          uuid.UUID    `json:"id"`
	ScanID      uuid.UUID    `json:"scan_id"`
	CreatedBy   uuid.UUID    `json:"created_by"`
	Format      ReportFormat `json:"format"`
	Filename    string       `json:"filename"`
	ContentType string       `json:"content_type"`
	Content     []byte       `json:"content"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.ScanID,
		arg.CreatedBy,
		arg.Format,
		arg.Filename,
		arg.ContentType,
		arg.Content,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.CreatedBy,
		&i.Format,
		&i.Filename,
		&i.ContentType,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createScan = `-- name: CreateScan :one
INSERT INTO scans (
    id,
    project_id,
    created_by,
    url
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    project_id,
    created_by,
    url,
    status,
    page_title,
    automated_score,
    critical_count,
    serious_count,
    moderate_count,
    minor_count,
    error_message,
    duration_ms,
    created_at,
    updated_at
`

type CreateScanParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	CreatedBy uuid.UUID `json:"created_by"`
	Url       string    `json:"url"`
}

type CreateScanRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	Url            string             `json:"url"`
	Status         ScanStatus         `json:"status"`
	PageTitle      string             `json:"page_title"`
	AutomatedScore int16              `json:"automated_score"`
	CriticalCount  int32              `json:"critical_count"`
	SeriousCount   int32              `json:"serious_count"`
	ModerateCount  int32              `json:"moderate_count"`
	MinorCount     int32              `json:"minor_count"`
	ErrorMessage   string             `json:"error_message"`
	DurationMs     int64              `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (CreateScanRow, error) {
	row := q.db.QueryRow(ctx, createScan,
		arg.ID,
		arg.ProjectID,
		arg.CreatedBy,
		arg.Url,
	)
	var i CreateScanRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Url,
		&i.Status,
		&i.PageTitle,
		&i.AutomatedScore,
		&i.CriticalCount,
		&i.SeriousCount,
		&i.ModerateCount,
		&i.MinorCount,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScannedPage = `-- name: CreateScannedPage :one
INSERT INTO scanned_pages (
    id,
    scan_id,
    url,
    title,
    language
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    scan_id,
    url,
    title,
    language,
    created_at
`

type CreateScannedPageParams struct {
	ID       uuid.UUID `json:"id"`
	ScanID   uuid.UUID `json:"scan_id"`
	Url      string    `json:"url"`
	Title    string    `json:"title"`
	Language string    `json:"language"`
}

func (q *Queries) CreateScannedPage(ctx context.Context, arg CreateScannedPageParams) (ScannedPage, error) {
	row := q.db.QueryRow(ctx, createScannedPage,
		arg.ID,
		arg.ScanID,
		arg.Url,
		arg.Title,
		arg.Language,
	)
	var i ScannedPage
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.Url,
		&i.Title,
		&i.Language,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    user_id,
    token_hash,
    csrf_hash,
    user_agent,
    ip_address,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id,
    user_id,
    token_hash,
    csrf_hash,
    user_agent,
    ip_address,
    expires_at,
    last_used_at,
    created_at
`

type CreateSessionParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	CsrfHash  string             `json:"csrf_hash"`
	UserAgent string             `json:"user_agent"`
	IpAddress string             `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    name,
    email,
    password_hash
) VALUES (
    $1,
    $2,
    LOWER($3),
    $4
)
RETURNING
    id,
    name,
    email,
    password_hash,
    created_at,
    updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createViolation = `-- name: CreateViolation :one
INSERT INTO violations (
    id,
    scanned_page_id,
    rule_id,
    impact,
    description,
    help,
    help_url,
    tags
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    scanned_page_id,
    rule_id,
    impact,
    description,
    help,
    help_url,
    tags,
    review_status,
    notes,
    created_at,
    updated_at
`

type CreateViolationParams struct {
	ID            uuid.UUID       `json:"id"`
	ScannedPageID uuid.UUID       `json:"scanned_page_id"`
	RuleID        string          `json:"rule_id"`
	Impact        ViolationImpact `json:"impact"`
	Description   string          `json:"description"`
	Help          string          `json:"help"`
	HelpUrl       string          `json:"help_url"`
	Tags          []string        `json:"tags"`
}

func (q *Queries) CreateViolation(ctx context.Context, arg CreateViolationParams) (Violation, error) {
	row := q.db.QueryRow(ctx, createViolation,
		arg.ID,
		arg.ScannedPageID,
		arg.RuleID,
		arg.Impact,
		arg.Description,
		arg.Help,
		arg.HelpUrl,
		arg.Tags,
	)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.ScannedPageID,
		&i.RuleID,
		&i.Impact,
		&i.Description,
		&i.Help,
		&i.HelpUrl,
		&i.Tags,
		&i.ReviewStatus,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createViolationNode = `-- name: CreateViolationNode :one
INSERT INTO violation_nodes (
    id,
    violation_id,
    html,
    target,
    failure_summary
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    violation_id,
    html,
    target,
    failure_summary,
    created_at
`

type CreateViolationNodeParams struct {
	ID             uuid.UUID `json:"id"`
	ViolationID    uuid.UUID `json:"violation_id"`
	Html           string    `json:"html"`
	Target         []string  `json:"target"`
	FailureSummary string    `json:"failure_summary"`
}

func (q *Queries) CreateViolationNode(ctx context.Context, arg CreateViolationNodeParams) (ViolationNode, error) {
	row := q.db.QueryRow(ctx, createViolationNode,
		arg.ID,
		arg.ViolationID,
		arg.Html,
		arg.Target,
		arg.FailureSummary,
	)
	var i ViolationNode
	err := row.Scan(
		&i.ID,
		&i.ViolationID,
		&i.Html,
		&i.Target,
		&i.FailureSummary,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
  AND owner_id = $2
`

type DeleteProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.Exec(ctx, deleteProject, arg.ProjectID, arg.UserID)
	return err
}

const deleteScanForUser = `-- name: DeleteScanForUser :exec
DELETE FROM scans
WHERE id = $1
  AND EXISTS (
      SELECT 1
      FROM project_members
      WHERE project_members.project_id = scans.project_id
        AND project_members.user_id = $2
  )
`

type DeleteScanForUserParams struct {
	ScanID uuid.UUID `json:"scan_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteScanForUser(ctx context.Context, arg DeleteScanForUserParams) error {
	_, err := q.db.Exec(ctx, deleteScanForUser, arg.ScanID, arg.UserID)
	return err
}

const deleteScanReports = `-- name: DeleteScanReports :exec
DELETE FROM reports
WHERE scan_id = $1
`

func (q *Queries) DeleteScanReports(ctx context.Context, scanID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScanReports, scanID)
	return err
}

const deleteScanResults = `-- name: DeleteScanResults :exec
DELETE FROM scanned_pages
WHERE scan_id = $1
`

func (q *Queries) DeleteScanResults(ctx context.Context, scanID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScanResults, scanID)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const failScan = `-- name: FailScan :one
UPDATE scans
SET
    status = 'failed',
    error_message = $1,
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $2
  AND status <> 'cancelled'
RETURNING
    id,
    project_id,
    created_by,
    url,
    status,
    page_title,
    automated_score,
    critical_count,
    serious_count,
    moderate_count,
    minor_count,
    error_message,
    duration_ms,
    created_at,
    updated_at
`

type FailScanParams struct {
	ErrorMessage string    `json:"error_message"`
	ID           uuid.UUID `json:"id"`
}

type FailScanRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	Url            string             `json:"url"`
	Status         ScanStatus         `json:"status"`
	PageTitle      string             `json:"page_title"`
	AutomatedScore int16              `json:"automated_score"`
	CriticalCount  int32              `json:"critical_count"`
	SeriousCount   int32              `json:"serious_count"`
	ModerateCount  int32              `json:"moderate_count"`
	MinorCount     int32              `json:"minor_count"`
	ErrorMessage   string             `json:"error_message"`
	DurationMs     int64              `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FailScan(ctx context.Context, arg FailScanParams) (FailScanRow, error) {
	row := q.db.QueryRow(ctx, failScan, arg.ErrorMessage, arg.ID)
	var i FailScanRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Url,
		&i.Status,
		&i.PageTitle,
		&i.AutomatedScore,
		&i.CriticalCount,
		&i.SeriousCount,
		&i.ModerateCount,
		&i.MinorCount,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManualReviewForScan = `-- name: GetManualReviewForScan :one
SELECT
    manual_reviews.id,
    manual_reviews.scan_id,
    manual_reviews.status,
    manual_reviews.created_at,
    manual_reviews.updated_at
FROM manual_reviews
INNER JOIN scans
    ON scans.id = manual_reviews.scan_id
INNER JOIN project_members
    ON project_members.project_id = scans.project_id
WHERE manual_reviews.scan_id = $1
  AND project_members.user_id = $2
LIMIT 1
`

type GetManualReviewForScanParams struct {
	ScanID uuid.UUID `json:"scan_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetManualReviewForScan(ctx context.Context, arg GetManualReviewForScanParams) (ManualReview, error) {
	row := q.db.QueryRow(ctx, getManualReviewForScan, arg.ScanID, arg.UserID)
	var i ManualReview
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnedProject = `-- name: GetOwnedProject :one
SELECT
    id,
    owner_id,
    name,
    description,
    created_at,
    updated_at
FROM projects
WHERE id = $1
  AND owner_id = $2
LIMIT 1
`

type GetOwnedProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOwnedProject(ctx context.Context, arg GetOwnedProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getOwnedProject, arg.ProjectID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectForUser = `-- name: GetProjectForUser :one
SELECT
    projects.id,
    projects.owner_id,
    projects.name,
    projects.description,
    projects.created_at,
    projects.updated_at
FROM projects
INNER JOIN project_members
    ON project_members.project_id = projects.id
WHERE projects.id = $1
  AND project_members.user_id = $2
LIMIT 1
`

type GetProjectForUserParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForUser, arg.ProjectID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportForUser = `-- name: GetReportForUser :one
SELECT
    reports.id,
    reports.scan_id,
    reports.created_by,
    reports.format,
    reports.filename,
    reports.content_type,
    reports.content,
    reports.created_at
FROM reports
INNER JOIN scans
    ON scans.id = reports.scan_id
INNER JOIN project_members
    ON project_members.project_id = scans.project_id
WHERE reports.id = $1
  AND project_members.user_id = $2
LIMIT 1
`

type GetReportForUserParams struct {
	ReportID uuid.UUID `json:"report_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetReportForUser(ctx context.Context, arg GetReportForUserParams) (Report, error) {
	row := q.db.QueryRow(ctx, getReportForUser, arg.ReportID, arg.UserID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.CreatedBy,
		&i.Format,
		&i.Filename,
		&i.ContentType,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getScanByID = `-- name: GetScanByID :one
SELECT
    id,
    project_id,
    created_by,
    url,
    status,
    page_title,
    automated_score,
    critical_count,
    serious_count,
    moderate_count,
    minor_count,
    error_message,
    duration_ms,
    created_at,
    updated_at
FROM scans
WHERE id = $1
LIMIT 1
`

type GetScanByIDRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	Url            string             `json:"url"`
	Status         ScanStatus         `json:"status"`
	PageTitle      string             `json:"page_title"`
	AutomatedScore int16              `json:"automated_score"`
	CriticalCount  int32              `json:"critical_count"`
	SeriousCount   int32              `json:"serious_count"`
	ModerateCount  int32              `json:"moderate_count"`
	MinorCount     int32              `json:"minor_count"`
	ErrorMessage   string             `json:"error_message"`
	DurationMs     int64              `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetScanByID(ctx context.Context, id uuid.UUID) (GetScanByIDRow, error) {
	row := q.db.QueryRow(ctx, getScanByID, id)
	var i GetScanByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Url,
		&i.Status,
		&i.PageTitle,
		&i.AutomatedScore,
		&i.CriticalCount,
		&i.SeriousCount,
		&i.ModerateCount,
		&i.MinorCount,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScanForUser = `-- name: GetScanForUser :one
SELECT
    scans.id,
    scans.project_id,
    scans.created_by,
    scans.url,
    scans.status,
    scans.page_title,
    scans.automated_score,
    scans.critical_count,
    scans.serious_count,
    scans.moderate_count,
    scans.minor_count,
    scans.error_message,
    scans.duration_ms,
    scans.created_at,
    scans.updated_at
FROM scans
INNER JOIN project_members
    ON project_members.project_id = scans.project_id
WHERE scans.id = $1
  AND project_members.user_id = $2
LIMIT 1
`

type GetScanForUserParams struct {
	ScanID uuid.UUID `json:"scan_id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetScanForUserRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	Url            string             `json:"url"`
	Status         ScanStatus         `json:"status"`
	PageTitle      string             `json:"page_title"`
	AutomatedScore int16              `json:"automated_score"`
	CriticalCount  int32              `json:"critical_count"`
	SeriousCount   int32              `json:"serious_count"`
	ModerateCount  int32              `json:"moderate_count"`
	MinorCount     int32              `json:"minor_count"`
	ErrorMessage   string             `json:"error_message"`
	DurationMs     int64              `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetScanForUser(ctx context.Context, arg GetScanForUserParams) (GetScanForUserRow, error) {
	row := q.db.QueryRow(ctx, getScanForUser, arg.ScanID, arg.UserID)
	var i GetScanForUserRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Url,
		&i.Status,
		&i.PageTitle,
		&i.AutomatedScore,
		&i.CriticalCount,
		&i.SeriousCount,
		&i.ModerateCount,
		&i.MinorCount,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    id,
    user_id,
    token_hash,
    csrf_hash,
    user_agent,
    ip_address,
    expires_at,
    last_used_at,
    created_at
FROM sessions
WHERE token_hash = $1
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    name,
    email,
    password_hash,
    created_at,
    updated_at
FROM users
WHERE LOWER(email) = LOWER($1)
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    name,
    email,
    password_hash,
    created_at,
    updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getViolationForUser = `-- name: GetViolationForUser :one
SELECT
    violations.id,
    violations.scanned_page_id,
    violations.rule_id,
    violations.impact,
    violations.description,
    violations.help,
    violations.help_url,
    violations.tags,
    violations.review_status,
    violations.notes,
    violations.created_at,
    violations.updated_at
FROM violations
INNER JOIN scanned_pages
    ON scanned_pages.id = violations.scanned_page_id
INNER JOIN scans
    ON scans.id = scanned_pages.scan_id
INNER JOIN project_members
    ON project_members.project_id = scans.project_id
WHERE violations.id = $1
  AND project_members.user_id = $2
LIMIT 1
`

type GetViolationForUserParams struct {
	ViolationID uuid.UUID `json:"violation_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetViolationForUser(ctx context.Context, arg GetViolationForUserParams) (Violation, error) {
	row := q.db.QueryRow(ctx, getViolationForUser, arg.ViolationID, arg.UserID)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.ScannedPageID,
		&i.RuleID,
		&i.Impact,
		&i.Description,
		&i.Help,
		&i.HelpUrl,
		&i.Tags,
		&i.ReviewStatus,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listManualReviewItems = `-- name: ListManualReviewItems :many
SELECT
    id,
    manual_review_id,
    criterion,
    instruction,
    status,
    notes,
    position,
    created_at,
    updated_at
FROM manual_review_items
WHERE manual_review_id = $1
ORDER BY position
`

func (q *Queries) ListManualReviewItems(ctx context.Context, manualReviewID uuid.UUID) ([]ManualReviewItem, error) {
	rows, err := q.db.Query(ctx, listManualReviewItems, manualReviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManualReviewItem{}
	for rows.Next() {
		var i ManualReviewItem
		if err := rows.Scan(
			&i.ID,
			&i.ManualReviewID,
			&i.Criterion,
			&i.Instruction,
			&i.Status,
			&i.Notes,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT DISTINCT
    projects.id,
    projects.owner_id,
    projects.name,
    projects.description,
    projects.created_at,
    projects.updated_at
FROM projects
INNER JOIN project_members
    ON project_members.project_id = projects.id
WHERE project_members.user_id = $1
ORDER BY projects.updated_at DESC
`

func (q *Queries) ListProjectsByUser(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScansByProject = `-- name: ListScansByProject :many
SELECT
    scans.id,
    scans.project_id,
    scans.created_by,
    scans.url,
    scans.status,
    scans.page_title,
    scans.automated_score,
    scans.critical_count,
    scans.serious_count,
    scans.moderate_count,
    scans.minor_count,
    scans.error_message,
    scans.duration_ms,
    scans.created_at,
    scans.updated_at
FROM scans
INNER JOIN project_members
    ON project_members.project_id = scans.project_id
WHERE scans.project_id = $1
  AND project_members.user_id = $2
ORDER BY scans.created_at DESC
LIMIT $3
`

type ListScansByProjectParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	UserID      uuid.UUID `json:"user_id"`
	ResultLimit int32     `json:"result_limit"`
}

type ListScansByProjectRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	Url            string             `json:"url"`
	Status         ScanStatus         `json:"status"`
	PageTitle      string             `json:"page_title"`
	AutomatedScore int16              `json:"automated_score"`
	CriticalCount  int32              `json:"critical_count"`
	SeriousCount   int32              `json:"serious_count"`
	ModerateCount  int32              `json:"moderate_count"`
	MinorCount     int32              `json:"minor_count"`
	ErrorMessage   string             `json:"error_message"`
	DurationMs     int64              `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListScansByProject(ctx context.Context, arg ListScansByProjectParams) ([]ListScansByProjectRow, error) {
	rows, err := q.db.Query(ctx, listScansByProject, arg.ProjectID, arg.UserID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScansByProjectRow{}
	for rows.Next() {
		var i ListScansByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CreatedBy,
			&i.Url,
			&i.Status,
			&i.PageTitle,
			&i.AutomatedScore,
			&i.CriticalCount,
			&i.SeriousCount,
			&i.ModerateCount,
			&i.MinorCount,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScansByUser = `-- name: ListScansByUser :many
SELECT
    scans.id,
    scans.project_id,
    scans.created_by,
    scans.url,
    scans.status,
    scans.page_title,
    scans.automated_score,
    scans.critical_count,
    scans.serious_count,
    scans.moderate_count,
    scans.minor_count,
    scans.error_message,
    scans.duration_ms,
    scans.created_at,
    scans.updated_at
FROM scans
INNER JOIN project_members
    ON project_members.project_id = scans.project_id
WHERE project_members.user_id = $1
ORDER BY scans.created_at DESC
LIMIT $2
`

type ListScansByUserParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ResultLimit int32     `json:"result_limit"`
}

type ListScansByUserRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	Url            string             `json:"url"`
	Status         ScanStatus         `json:"status"`
	PageTitle      string             `json:"page_title"`
	AutomatedScore int16              `json:"automated_score"`
	CriticalCount  int32              `json:"critical_count"`
	SeriousCount   int32              `json:"serious_count"`
	ModerateCount  int32              `json:"moderate_count"`
	MinorCount     int32              `json:"minor_count"`
	ErrorMessage   string             `json:"error_message"`
	DurationMs     int64              `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListScansByUser(ctx context.Context, arg ListScansByUserParams) ([]ListScansByUserRow, error) {
	rows, err := q.db.Query(ctx, listScansByUser, arg.UserID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScansByUserRow{}
	for rows.Next() {
		var i ListScansByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CreatedBy,
			&i.Url,
			&i.Status,
			&i.PageTitle,
			&i.AutomatedScore,
			&i.CriticalCount,
			&i.SeriousCount,
			&i.ModerateCount,
			&i.MinorCount,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViolationNodes = `-- name: ListViolationNodes :many
SELECT
    id,
    violation_id,
    html,
    target,
    failure_summary,
    created_at
FROM violation_nodes
WHERE violation_id = $1
ORDER BY created_at
`

func (q *Queries) ListViolationNodes(ctx context.Context, violationID uuid.UUID) ([]ViolationNode, error) {
	rows, err := q.db.Query(ctx, listViolationNodes, violationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViolationNode{}
	for rows.Next() {
		var i ViolationNode
		if err := rows.Scan(
			&i.ID,
			&i.ViolationID,
			&i.Html,
			&i.Target,
			&i.FailureSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViolationsForScan = `-- name: ListViolationsForScan :many
SELECT
    violations.id,
    violations.scanned_page_id,
    violations.rule_id,
    violations.impact,
    violations.description,
    violations.help,
    violations.help_url,
    violations.tags,
    violations.review_status,
    violations.notes,
    violations.created_at,
    violations.updated_at
FROM violations
INNER JOIN scanned_pages
    ON scanned_pages.id = violations.scanned_page_id
INNER JOIN scans
    ON scans.id = scanned_pages.scan_id
INNER JOIN project_members
    ON project_members.project_id = scans.project_id
WHERE scans.id = $1
  AND project_members.user_id = $2
ORDER BY
    CASE violations.impact
        WHEN 'critical' THEN 1
        WHEN 'serious' THEN 2
        WHEN 'moderate' THEN 3
        WHEN 'minor' THEN 4
    END,
    violations.rule_id
`

type ListViolationsForScanParams struct {
	ScanID uuid.UUID `json:"scan_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ListViolationsForScan(ctx context.Context, arg ListViolationsForScanParams) ([]Violation, error) {
	rows, err := q.db.Query(ctx, listViolationsForScan, arg.ScanID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Violation{}
	for rows.Next() {
		var i Violation
		if err := rows.Scan(
			&i.ID,
			&i.ScannedPageID,
			&i.RuleID,
			&i.Impact,
			&i.Description,
			&i.Help,
			&i.HelpUrl,
			&i.Tags,
			&i.ReviewStatus,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScanRunning = `-- name: MarkScanRunning :one
UPDATE scans
SET
    status = 'running',
    error_message = '',
    started_at = NOW(),
    completed_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND status IN ('queued', 'failed')
RETURNING
    id,
    project_id,
    created_by,
    url,
    status,
    page_title,
    automated_score,
    critical_count,
    serious_count,
    moderate_count,
    minor_count,
    error_message,
    duration_ms,
    created_at,
    updated_at
`

type MarkScanRunningRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	Url            string             `json:"url"`
	Status         ScanStatus         `json:"status"`
	PageTitle      string             `json:"page_title"`
	AutomatedScore int16              `json:"automated_score"`
	CriticalCount  int32              `json:"critical_count"`
	SeriousCount   int32              `json:"serious_count"`
	ModerateCount  int32              `json:"moderate_count"`
	MinorCount     int32              `json:"minor_count"`
	ErrorMessage   string             `json:"error_message"`
	DurationMs     int64              `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkScanRunning(ctx context.Context, id uuid.UUID) (MarkScanRunningRow, error) {
	row := q.db.QueryRow(ctx, markScanRunning, id)
	var i MarkScanRunningRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Url,
		&i.Status,
		&i.PageTitle,
		&i.AutomatedScore,
		&i.CriticalCount,
		&i.SeriousCount,
		&i.ModerateCount,
		&i.MinorCount,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const refreshManualReviewStatus = `-- name: RefreshManualReviewStatus :exec
UPDATE manual_reviews
SET
    status = CASE
        WHEN EXISTS (
            SELECT 1
            FROM manual_review_items
            WHERE manual_review_items.manual_review_id =
                $1
              AND manual_review_items.status = 'failed'
        ) THEN 'failed'::review_status
        WHEN EXISTS (
            SELECT 1
            FROM manual_review_items
            WHERE manual_review_items.manual_review_id =
                $1
              AND manual_review_items.status = 'pending'
        ) THEN 'pending'::review_status
        ELSE 'passed'::review_status
    END,
    updated_at = NOW()
WHERE manual_reviews.id = $1
`

func (q *Queries) RefreshManualReviewStatus(ctx context.Context, targetManualReviewID uuid.UUID) error {
	_, err := q.db.Exec(ctx, refreshManualReviewStatus, targetManualReviewID)
	return err
}

const resetManualReview = `-- name: ResetManualReview :exec
UPDATE manual_review_items
SET
    status = 'pending',
    notes = '',
    updated_at = NOW()
WHERE manual_review_items.manual_review_id = (
    SELECT manual_reviews.id
    FROM manual_reviews
    WHERE manual_reviews.scan_id = $1
)
`

func (q *Queries) ResetManualReview(ctx context.Context, scanID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetManualReview, scanID)
	return err
}

const resetManualReviewStatus = `-- name: ResetManualReviewStatus :exec
UPDATE manual_reviews
SET
    status = 'pending',
    updated_at = NOW()
WHERE scan_id = $1
`

func (q *Queries) ResetManualReviewStatus(ctx context.Context, scanID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetManualReviewStatus, scanID)
	return err
}

const resetScanForRetry = `-- name: ResetScanForRetry :one
UPDATE scans
SET
    status = 'queued',
    page_title = '',
    automated_score = 0,
    critical_count = 0,
    serious_count = 0,
    moderate_count = 0,
    minor_count = 0,
    duration_ms = 0,
    error_message = '',
    started_at = NULL,
    completed_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND status IN ('failed', 'cancelled')
  AND EXISTS (
      SELECT 1
      FROM project_members
      WHERE project_members.project_id = scans.project_id
        AND project_members.user_id = $2
  )
RETURNING
    id,
    project_id,
    created_by,
    url,
    status,
    page_title,
    automated_score,
    critical_count,
    serious_count,
    moderate_count,
    minor_count,
    error_message,
    duration_ms,
    created_at,
    updated_at
`

type ResetScanForRetryParams struct {
	ScanID uuid.UUID `json:"scan_id"`
	UserID uuid.UUID `json:"user_id"`
}

type ResetScanForRetryRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	Url            string             `json:"url"`
	Status         ScanStatus         `json:"status"`
	PageTitle      string             `json:"page_title"`
	AutomatedScore int16              `json:"automated_score"`
	CriticalCount  int32              `json:"critical_count"`
	SeriousCount   int32              `json:"serious_count"`
	ModerateCount  int32              `json:"moderate_count"`
	MinorCount     int32              `json:"minor_count"`
	ErrorMessage   string             `json:"error_message"`
	DurationMs     int64              `json:"duration_ms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ResetScanForRetry(ctx context.Context, arg ResetScanForRetryParams) (ResetScanForRetryRow, error) {
	row := q.db.QueryRow(ctx, resetScanForRetry, arg.ScanID, arg.UserID)
	var i ResetScanForRetryRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Url,
		&i.Status,
		&i.PageTitle,
		&i.AutomatedScore,
		&i.CriticalCount,
		&i.SeriousCount,
		&i.ModerateCount,
		&i.MinorCount,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateManualReviewItem = `-- name: UpdateManualReviewItem :one
UPDATE manual_review_items
SET
    status = $1,
    notes = $2,
    updated_at = NOW()
WHERE manual_review_items.id = $3
  AND EXISTS (
      SELECT 1
      FROM manual_reviews
      INNER JOIN scans
          ON scans.id = manual_reviews.scan_id
      INNER JOIN project_members
          ON project_members.project_id = scans.project_id
      WHERE manual_reviews.id = manual_review_items.manual_review_id
        AND project_members.user_id = $4
  )
RETURNING
    manual_review_items.id,
    manual_review_items.manual_review_id,
    manual_review_items.criterion,
    manual_review_items.instruction,
    manual_review_items.status,
    manual_review_items.notes,
    manual_review_items.position,
    manual_review_items.created_at,
    manual_review_items.updated_at
`

type UpdateManualReviewItemParams struct {
	Status ReviewStatus `json:"status"`
	Notes  string       `json:"notes"`
	ItemID uuid.UUID    `json:"item_id"`
	UserID uuid.UUID    `json:"user_id"`
}

func (q *Queries) UpdateManualReviewItem(ctx context.Context, arg UpdateManualReviewItemParams) (ManualReviewItem, error) {
	row := q.db.QueryRow(ctx, updateManualReviewItem,
		arg.Status,
		arg.Notes,
		arg.ItemID,
		arg.UserID,
	)
	var i ManualReviewItem
	err := row.Scan(
		&i.ID,
		&i.ManualReviewID,
		&i.Criterion,
		&i.Instruction,
		&i.Status,
		&i.Notes,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name = $1,
    description = $2,
    updated_at = NOW()
WHERE id = $3
  AND owner_id = $4
RETURNING
    id,
    owner_id,
    name,
    description,
    created_at,
    updated_at
`

type UpdateProjectParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	ProjectID   uuid.UUID `json:"project_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.ProjectID,
		arg.UserID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateViolationReview = `-- name: UpdateViolationReview :one
UPDATE violations
SET
    review_status = $1,
    notes = $2,
    updated_at = NOW()
WHERE violations.id = $3
  AND EXISTS (
      SELECT 1
      FROM scanned_pages
      INNER JOIN scans
          ON scans.id = scanned_pages.scan_id
      INNER JOIN project_members
          ON project_members.project_id = scans.project_id
      WHERE scanned_pages.id = violations.scanned_page_id
        AND project_members.user_id = $4
  )
RETURNING
    violations.id,
    violations.scanned_page_id,
    violations.rule_id,
    violations.impact,
    violations.description,
    violations.help,
    violations.help_url,
    violations.tags,
    violations.review_status,
    violations.notes,
    violations.created_at,
    violations.updated_at
`

type UpdateViolationReviewParams struct {
	ReviewStatus ReviewStatus `json:"review_status"`
	Notes        string       `json:"notes"`
	ViolationID  uuid.UUID    `json:"violation_id"`
	UserID       uuid.UUID    `json:"user_id"`
}

func (q *Queries) UpdateViolationReview(ctx context.Context, arg UpdateViolationReviewParams) (Violation, error) {
	row := q.db.QueryRow(ctx, updateViolationReview,
		arg.ReviewStatus,
		arg.Notes,
		arg.ViolationID,
		arg.UserID,
	)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.ScannedPageID,
		&i.RuleID,
		&i.Impact,
		&i.Description,
		&i.Help,
		&i.HelpUrl,
		&i.Tags,
		&i.ReviewStatus,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
