// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error
	CancelScan(ctx context.Context, arg CancelScanParams) (CancelScanRow, error)
	CompleteScan(ctx context.Context, arg CompleteScanParams) (CompleteScanRow, error)
	CountRecentScansByUser(ctx context.Context, arg CountRecentScansByUserParams) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error
	CreateManualReview(ctx context.Context, arg CreateManualReviewParams) (ManualReview, error)
	CreateManualReviewItem(ctx context.Context, arg CreateManualReviewItemParams) (ManualReviewItem, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateScan(ctx context.Context, arg CreateScanParams) (CreateScanRow, error)
	CreateScannedPage(ctx context.Context, arg CreateScannedPageParams) (ScannedPage, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateViolation(ctx context.Context, arg CreateViolationParams) (Violation, error)
	CreateViolationNode(ctx context.Context, arg CreateViolationNodeParams) (ViolationNode, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	DeleteScanForUser(ctx context.Context, arg DeleteScanForUserParams) error
	DeleteScanReports(ctx context.Context, scanID uuid.UUID) error
	DeleteScanResults(ctx context.Context, scanID uuid.UUID) error
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	FailScan(ctx context.Context, arg FailScanParams) (FailScanRow, error)
	GetManualReviewForScan(ctx context.Context, arg GetManualReviewForScanParams) (ManualReview, error)
	GetOwnedProject(ctx context.Context, arg GetOwnedProjectParams) (Project, error)
	GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (Project, error)
	GetReportForUser(ctx context.Context, arg GetReportForUserParams) (Report, error)
	GetScanByID(ctx context.Context, id uuid.UUID) (GetScanByIDRow, error)
	GetScanForUser(ctx context.Context, arg GetScanForUserParams) (GetScanForUserRow, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetViolationForUser(ctx context.Context, arg GetViolationForUserParams) (Violation, error)
	ListManualReviewItems(ctx context.Context, manualReviewID uuid.UUID) ([]ManualReviewItem, error)
	ListProjectsByUser(ctx context.Context, userID uuid.UUID) ([]Project, error)
	ListScansByProject(ctx context.Context, arg ListScansByProjectParams) ([]ListScansByProjectRow, error)
	ListScansByUser(ctx context.Context, arg ListScansByUserParams) ([]ListScansByUserRow, error)
	ListViolationNodes(ctx context.Context, violationID uuid.UUID) ([]ViolationNode, error)
	ListViolationsForScan(ctx context.Context, arg ListViolationsForScanParams) ([]Violation, error)
	MarkScanRunning(ctx context.Context, id uuid.UUID) (MarkScanRunningRow, error)
	RefreshManualReviewStatus(ctx context.Context, targetManualReviewID uuid.UUID) error
	ResetManualReview(ctx context.Context, scanID uuid.UUID) error
	ResetManualReviewStatus(ctx context.Context, scanID uuid.UUID) error
	ResetScanForRetry(ctx context.Context, arg ResetScanForRetryParams) (ResetScanForRetryRow, error)
	TouchSession(ctx context.Context, id uuid.UUID) error
	UpdateManualReviewItem(ctx context.Context, arg UpdateManualReviewItemParams) (ManualReviewItem, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateViolationReview(ctx context.Context, arg UpdateViolationReviewParams) (Violation, error)
}

var _ Querier = (*Queries)(nil)
